// Date: 4/2/2015 7:07:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.vfluff5.netcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRouter extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer Top;
  
  public ModelRouter()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 9, 4, 9);
      Base.setRotationPoint(-5F, 20F, -4F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 36, 13);
      Side1.addBox(0F, 0F, 0F, 7, 4, 7);
      Side1.setRotationPoint(-2F, 20F, -3F);
      Side1.setTextureSize(64, 64);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 36, 25);
      Side2.addBox(0F, 0F, 0F, 7, 4, 7);
      Side2.setRotationPoint(-4F, 20F, -5F);
      Side2.setTextureSize(64, 64);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 36, 37);
      Side3.addBox(0F, 0F, 0F, 7, 4, 7);
      Side3.setRotationPoint(-4F, 20F, -1F);
      Side3.setTextureSize(64, 64);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Side4 = new ModelRenderer(this, 36, 49);
      Side4.addBox(0F, 0F, 0F, 7, 4, 7);
      Side4.setRotationPoint(-6F, 20F, -3F);
      Side4.setTextureSize(64, 64);
      Side4.mirror = true;
      setRotation(Side4, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 14);
      Top.addBox(0F, 0F, 0F, 7, 1, 7);
      Top.setRotationPoint(-4F, 19F, -3F);
      Top.setTextureSize(64, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    Top.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
